import { AiFillStar } from "react-icons/ai";
import { CiHeart } from "react-icons/ci";
import { FaCartShopping } from "react-icons/fa6";


const data = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "160",
    prevPrice: "2599",
    newPrice: "1000",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "101",
    prevPrice: "1500",
    newPrice: "1000",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1599",
    newPrice: "1000",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "121",
    prevPrice: "2999",
    newPrice: "2000",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "100",
    prevPrice: "800",
    newPrice: "500",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "1k",
    prevPrice: "1200",
    newPrice: "1000",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "850",
    newPrice: "500",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "120",
    prevPrice: "1099",
    newPrice: "1000",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "2000",
    newPrice: "1500",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "12k",
    prevPrice: "1200",
    newPrice: "1099",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "110",
    prevPrice: "2000",
    newPrice: "1500",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "120",
    prevPrice: "1599",
    newPrice: "1500",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1999",
    newPrice: "1500",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1400",
    newPrice: "1200",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1599",
    newPrice: "1200",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1599",
    newPrice: "1200",
    company: "Vans",
    color: "red",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1599",
    newPrice: "1200",
    company: "Vans",
    color: "white",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1600",
    newPrice: "1299",
    company: "Vans",
    color: "blue",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1600",
    newPrice: "299",
    company: "Nike",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1600",
    newPrice: "2299",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },
 {
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1099",
    newPrice: "1000",
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/81CmZsYGooL._AC_UL480_FMwebp_QL65_.jpg",
    title: " Men's King Pro",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1099",
    newPrice: "1000",
    company: "Campus",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61+u7BBiaxL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Men's First Running Shoes",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1099",
    newPrice: "1000",
    company: "Campus",
    color: "black",
    category: "sneakers",
  },
  {
    img: "  https://m.media-amazon.com/images/I/51h9WE-QubL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Slippers For Women ",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1500",
    newPrice: "499",
    company: "Campus",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71X8gXn3VXL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Slippers For Women ",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "123",
    prevPrice: "1500",
    newPrice: "1299",
    company: "Campus",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71+fhvtoQCL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Sandals for men ",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "12k",
    prevPrice: "1500",
    newPrice: "1299",
    company: "Sparx",
    color: "black",
    category: "sandals",
  },
  {
    img: " https://m.media-amazon.com/images/I/81QTpP7ypNL._AC_UL480_FMwebp_QL65_.jpg",
    title: "men's Sneaker  ",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "12k",
    prevPrice: "1500",
    newPrice: "1299",
    company: "Sparx",
    color: "black",
    category: "sneakers",
  },
  {
    img: " https://m.media-amazon.com/images/I/61VfyBo6UcL._AC_UL480_FMwebp_QL65_.jpg",
    title: "men's Sneaker  ",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "12k",
    prevPrice: "1500",
    newPrice: "1299",
    company: "RedTape",
    color: "black",
    category: "sneakers",
  },
  {
    img: " https://m.media-amazon.com/images/I/71ETD6wm-bL._AC_UL480_FMwebp_QL65_.jpg",
    title: "men's Sliders",
    star: <AiFillStar className="rating-star" />,
    heart:<CiHeart/>,
    cart:<FaCartShopping/>,
    reviews: "12k",
    prevPrice: "1500",
    newPrice: "1299",
    company: "RedTape",
    color: "black",
    category: "flats",
  },
];

export default data;